apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: default
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name: Consul
      status: Connected to Consul running in Kubernetes
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: YTllMTBiM2I5NjQ1NTRkMjdiYzRmMjM0ODhmMDY1YThlNmNhYzIzM2FlYjI2ZTVjMjM0NDY1NTMyNDA4MGQ1ZWQwMGJmZGNjNTZmZDA2NjA2NTk2N2NiZTg4ODk3MTVlYmFlMQ==
  # app specific configuration
